/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import config.ReadAndWrite;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import pay.Pay;
import pay.WXPayUtil;
import pay.WxPay;
import pay.WxQuery;

/**
 *
 * @author vip
 */
public class MainUI extends javax.swing.JFrame {

    /**
     * Creates new form UI
     */
    public MainUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTAShow = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTAShow2 = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jTFOrderId = new javax.swing.JTextField();
        jTFAmt = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTFCode = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jBPay = new javax.swing.JButton();
        jBQuery = new javax.swing.JButton();
        jBRefund = new javax.swing.JButton();
        jCBFlag = new javax.swing.JCheckBox();

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("POS模拟器");

        jTAShow.setColumns(20);
        jTAShow.setFont(new java.awt.Font("宋体", 0, 18)); // NOI18N
        jTAShow.setRows(5);
        jScrollPane1.setViewportView(jTAShow);

        jLabel4.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
        jLabel4.setText("请求报文");

        jTAShow2.setColumns(20);
        jTAShow2.setFont(new java.awt.Font("宋体", 0, 18)); // NOI18N
        jTAShow2.setRows(5);
        jScrollPane3.setViewportView(jTAShow2);

        jLabel6.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
        jLabel6.setText("响应报文");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1))))
        );

        jTFOrderId.setFont(new java.awt.Font("宋体", 0, 18)); // NOI18N
        jTFOrderId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFOrderIdActionPerformed(evt);
            }
        });

        jTFAmt.setFont(new java.awt.Font("宋体", 0, 18)); // NOI18N
        jTFAmt.setText("1");

        jLabel1.setFont(new java.awt.Font("宋体", 0, 18)); // NOI18N
        jLabel1.setText(" 金额/分");

        jLabel2.setFont(new java.awt.Font("宋体", 0, 18)); // NOI18N
        jLabel2.setText(" 二维码");

        jTFCode.setFont(new java.awt.Font("宋体", 0, 18)); // NOI18N

        jLabel3.setFont(new java.awt.Font("宋体", 0, 18)); // NOI18N
        jLabel3.setText(" 订单号");

        jBPay.setFont(new java.awt.Font("宋体", 0, 18)); // NOI18N
        jBPay.setText("扫码支付");
        jBPay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBPayActionPerformed(evt);
            }
        });

        jBQuery.setFont(new java.awt.Font("宋体", 0, 18)); // NOI18N
        jBQuery.setText("扫码查询");
        jBQuery.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBQueryActionPerformed(evt);
            }
        });

        jBRefund.setFont(new java.awt.Font("宋体", 0, 18)); // NOI18N
        jBRefund.setText("扫码退款");
        jBRefund.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBRefundActionPerformed(evt);
            }
        });

        jCBFlag.setText("机构接入标识");

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jCBFlag, org.jdesktop.beansbinding.ELProperty.create("${selected}"), jCBFlag, org.jdesktop.beansbinding.BeanProperty.create("selected"));
        bindingGroup.addBinding(binding);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTFAmt)
                            .addComponent(jTFOrderId)
                            .addComponent(jTFCode)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jCBFlag)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jBQuery, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 301, Short.MAX_VALUE)
                            .addComponent(jBPay, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jBRefund, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTFOrderId, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTFAmt, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTFCode, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(26, 26, 26)
                .addComponent(jCBFlag)
                .addGap(26, 26, 26)
                .addComponent(jBPay, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jBQuery, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jBRefund, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(133, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTFOrderIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFOrderIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFOrderIdActionPerformed

    private ReadAndWrite rw =null;
    private Map<String, String> request = null ;
    private String response = null;;
    
    private void jBPayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBPayActionPerformed
        // TODO add your handling code here:    
        jTAShow.setText("");
        jTAShow2.setText("");
        
        rw = new ReadAndWrite();
        request = rw.read();
        
        SimpleDateFormat sdf1 = new SimpleDateFormat("yyMMdd");
        Date date1 = new Date();
        batchNo = sdf1.format(date1);
//        batchNo = request.get("batchNo");
        systrace = WXPayUtil.strAddOne(request.get("systrace"));
        try {
            rw.write(batchNo, systrace);
        } catch (IOException ex) {
            Logger.getLogger(MainUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        SimpleDateFormat sdf = new SimpleDateFormat("yyyyMMdd");
        Date date = new Date();
        orderId = sdf.format(date) + batchNo + systrace;
        jTFOrderId.setText(orderId);
        
        authCode = jTFCode.getText();
        amt = Long.parseLong(jTFAmt.getText());
        jTAShow.append("begin ...\n");

        if (authCode != null && orderId != null && amt != 0L && authCode.length() != 0 && orderId.length() != 0) {
            request.put("orderId", orderId.trim());
            request.put("barcode", authCode.trim());
            request.put("txnAmt", String.valueOf(amt));
        } else {
            jTAShow2.append("rc :91\n");
            jTAShow2.append("rc_detail:参数缺失\n");
            return;
        }
        
        if (jCBFlag.isSelected()) {
            request.put("orgFlag", String.valueOf(1));
        }

        try {
            Pay pay = new Pay();    
            String show = request.toString();   
            String show2 = show.replace(",", ",\n").replace("{", "{\n").replace("}", "\n}");
            jTAShow.append(show2);
            response = pay.barcodePay(request);    
            jTAShow2.append( response.replace(",", ",\n").replace("{", "{\n").replace("}", "\n}"));
        } catch (Exception e) {
            jTAShow2.append(e.getMessage());
        }
    }//GEN-LAST:event_jBPayActionPerformed

    private void jBQueryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBQueryActionPerformed
        // TODO add your handling code here:
        jTAShow.setText("");
        jTAShow2.setText("");
        
        rw = new ReadAndWrite();
        request = rw.read();
        
        SimpleDateFormat sdf1 = new SimpleDateFormat("yyMMdd");
        Date date1 = new Date();
        batchNo = sdf1.format(date1);
//        batchNo = request.get("batchNo");
        systrace = WXPayUtil.strAddOne(request.get("systrace"));
        try {
            rw.write(batchNo, systrace);
        } catch (IOException ex) {
            Logger.getLogger(MainUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        orderId = jTFOrderId.getText();
        jTAShow.append("begin ...\n");
        
        if ( orderId != null &&orderId.length() != 0) {
            request.put("orderId", orderId.trim());
        } else {
            jTAShow2.append("rc :91\n");
            jTAShow2.append("rc_detail:参数缺失\n");
            return;
        }
        if (jCBFlag.isSelected()) {
            request.put("orgFlag", String.valueOf(1));
        }
        try {
            Pay pay = new Pay();
            String show = request.toString();
            String show2 = show.replace(",", ",\n").replace("{", "{\n").replace("}", "\n}");
            jTAShow.append(show2);
            response = pay.barcodeQuery(request);
            jTAShow2.append( response.replace(",", ",\n").replace("{", "{\n").replace("}", "\n}"));
//            jTAShow2.append(response);
        } catch (Exception e) {
            jTAShow2.append(e.getMessage());
        }
    }//GEN-LAST:event_jBQueryActionPerformed

    private void jBRefundActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBRefundActionPerformed
        // TODO add your handling code here:
        jTAShow.setText("");
        jTAShow2.setText("");
        
        rw = new ReadAndWrite();
        request = rw.read();
        SimpleDateFormat sdf1 = new SimpleDateFormat("yyMMdd");
        Date date1 = new Date();
        batchNo = sdf1.format(date1);
//        batchNo = request.get("batchNo");
        systrace = WXPayUtil.strAddOne(request.get("systrace"));
        try {
            rw.write(batchNo, systrace);
        } catch (IOException ex) {
            Logger.getLogger(MainUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        orderId = jTFOrderId.getText();
        jTAShow.append("begin ...\n");

        if ( orderId != null &&orderId.length() != 0) {
            request.put("orderId", orderId.trim());
        } else {
            jTAShow2.append("rc :91\n");
            jTAShow2.append("rc_detail:参数缺失\n");
            return;
        }
        if (jCBFlag.isSelected()) {
            request.put("orgFlag", String.valueOf(1));
        }
        try {
            Pay pay = new Pay();
//            jTAShow.append(request.toString());
            String show = request.toString();
            String show2 = show.replace(",", ",\n").replace("{", "{\n").replace("}", "\n}");
            jTAShow.append(show2);
            
            
            response = pay.barcodeRefund(request);
            
            
            jTAShow2.append( response.replace(",", ",\n").replace("{", "{\n").replace("}", "\n}"));
//            jTAShow2.append(response);
        } catch (Exception e) {
            jTAShow2.append(e.getMessage());
        }
    }//GEN-LAST:event_jBRefundActionPerformed

    private boolean doCheck(String id){
        switch(id){
            case "841100":
                SimpleDateFormat sdf = new SimpleDateFormat("yyyyMMdd");
                Date date = new Date();
                orderId = sdf.format(date) + batchNo + systrace;
                jTFOrderId.setText(orderId);
                authCode = jTFCode.getText();
                amt = Long.parseLong(jTFAmt.getText());

                if (authCode != null && orderId != null && amt != 0L && authCode.length() != 0 && orderId.length() != 0) {
                    request.put("orderId", orderId.trim());
                    request.put("barcode", authCode.trim());
                    request.put("txnAmt", String.valueOf(amt));
                    request.put("txnId", id);
                    return true;
                }
                break;
            case "841110":
            case "841500":
                orderId = jTFOrderId.getText();
                if ( orderId != null &&orderId.length() != 0) {
                     request.put("orderId", orderId.trim());
                     request.put("txnId", id);
                     return true;
                }
                break;
            default:
        }
        
        jTAShow2.append("rc :91\n");
        jTAShow2.append("rc_detail:参数缺失\n");
        return false;

    }
    
    private String doTrans(String id) throws Exception{
        try{
            switch(id){
                case "841100":
                    WxPay wxPay = new WxPay();
                    return wxPay.handle(request);
                case "841500":
                case "841110":
                    WxQuery wxQuery = new WxQuery();
                    return wxQuery.handle(request);
                default:
                    return null;
            }
        }catch(Exception ex){
            throw new Exception(ex);
        }
        
    }
    
    private void doShow(String id){
        
        jTAShow.setText("");
        jTAShow2.setText("");
        
        rw = new ReadAndWrite();
        request = rw.read();
        SimpleDateFormat sdf1 = new SimpleDateFormat("yyMMdd");
        Date date1 = new Date();
        batchNo = sdf1.format(date1);
        systrace = WXPayUtil.strAddOne(request.get("systrace"));
        try {
            rw.write(batchNo, systrace);
        } catch (IOException ex) {
            Logger.getLogger(MainUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        jTAShow.append("begin ...\n");

        if ( !doCheck(id) ){
            return ;
        }        
        
        if (jCBFlag.isSelected()) {
            request.put("orgFlag", String.valueOf(1));
        }
        try {
    
            String show = request.toString();
            String show2 = show.replace(",", ",\n").replace("{", "{\n").replace("}", "\n}");
            jTAShow.append(show2);
            response = doTrans(id);
            jTAShow2.append( response.replace(",", ",\n").replace("{", "{\n").replace("}", "\n}"));

        } catch (Exception e) {
            jTAShow2.append(e.getMessage());
        }
        
    }
        /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainUI().setVisible(true);
            }
        });
    }

    private String authCode = null;
    private String orderId = null;
    private Long amt = 0L;
    private String batchNo = null;
    private String systrace = null;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBPay;
    private javax.swing.JButton jBQuery;
    private javax.swing.JButton jBRefund;
    private javax.swing.JCheckBox jCBFlag;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTAShow;
    private javax.swing.JTextArea jTAShow2;
    private javax.swing.JTextField jTFAmt;
    private javax.swing.JTextField jTFCode;
    private javax.swing.JTextField jTFOrderId;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
